### ISSUE TITLE
Software license missing for project

### ISSUE THREAD

**Issue by prometheas** [CareLuLu/react-native-web-jsonschema-form#171]
I’m rather excited to a found this project, and am interested in using it for an app I’m working on. Thing is, it’s a closed-source app, so we must be careful about the licenses of libraries we use (no GPL, etc.), so it’d be great to have that info.

In any case, this seems to be shaping up nicely, fwiw!

**Comment by CareLuLu-Gabriel** [comment]
@prometheas thank you for pointing that out! The project uses MIT license. It's was in the `package.json` but it's a good idea to add to the `README.md`.
