### ISSUE TITLE
react-native-inti

### ISSUE THREAD

**Issue by AbanoubAshraaf** [CareLuLu/react-native-web-jsonschema-form#201]
Is there any way to run this package on ejected react native projects that created by react-native-init not by expo

**Comment by CareLuLu-Gabriel** [comment]
@AbanoubAshraaf I haven't tried. I believe you can probably make it work. I think the only components that depend on `Expo` are `Image` and `Dropzone`.

**Comment by AbanoubAshraaf** [comment]
I made it work , but I'm facing some problems like :-

1- can't able to print lists

2- when tried to assign ref from references that created in definition key
to one of  properties key it not working,

3- when assign title to the object of field to print it  alternate name of
thia filed it still print the name

**Comment by CareLuLu-Gabriel** [comment]
@AbanoubAshraaf if you post a link to an example project I can help you.
