### ISSUE TITLE
Styling Help

### ISSUE THREAD

**Issue by runticle** [CareLuLu/react-native-web-jsonschema-form#237]
https://www.carelulu.com/tech-request/1428

Hi!

Thanks for sharing this library, it's really useful to have this working with React Native Web.

However, despite the brilliant examples in some of the other issue threads (that have helped immensely with customWidgets and the lark!), I cannot figure out how to style the form.

It feels like I am guessing the names of components and getting it wrong. I have inserted custom widgets for all my use cases, so they all look fine. I think I can work out how to pass in a submitButton, and fire the correct calls, but I cannot figure out how to style the titles above each widget.

Are there any guides that lay out how to actually target each element to style?

Something like this, but not this?

```
<Form
...props
style={
    title: {
        color: 'blue'
...
```

Thanks, really like the package so far!
Alfie

**Comment by CareLuLu-Gabriel** [comment]
@runticle I'm glad you found the library useful!

You can add styling to specific fields or groups of fields using `uiSchema`. It'd be something like this:

```js
const uiSchema = {
  '*': {
    'ui:titleProps': {
      style: { color: 'blue' },
    },
  },
  redField: {
    'ui:titleProps': {
      style: { color: 'red' },
    },
  },
};

const schema = {
  type: 'object',
  properties: {
    blueField1: { type: 'string' },
    redField: { type: 'string' },
    blueField2: { type: 'string' },
  },
};

const MyForm = props => (
  <Form
    {...props}
    schema={schema}
    uiSchema={uiSchema}
  />
);
```

**Comment by runticle** [comment]
Ah yes wonderful. Thanks for a super quick response! Am I being silly not knowing the prop I required specifically for title was `ui:titleProps` ?

**Comment by carelulu-igor** [comment]
Hi @runticle! You can refer to https://rjsf-team.github.io/react-jsonschema-form/ to find the right props for each component :)

**Comment by CareLuLu-Gabriel** [comment]
@runticle it wasn't silly :)

We actually have some custom properties that are not part https://rjsf-team.github.io/react-jsonschema-form/'s API. Some of them are:
`ui:titleProps`
`ui:widgetProps`
`ui:errorProps`

These allow you to pass `props` directly to the underlying components to give you more control (especially styling).
