### ISSUE TITLE
Expo errors creeping in to react-native-web project

### ISSUE THREAD

**Issue by runticle** [CareLuLu/react-native-web-jsonschema-form#243]
Hi there,

Me again, have fully integrated the library and it works really well. I am using it solely on web for now in our `react-native-web` project.

The trouble I am having now is I am unable to build the project in IOS or android. I was wondering if anyone has had these errors? 

![Screenshot 2021-05-20 at 11 30 48](https://user-images.githubusercontent.com/40716695/118966664-c4d21280-b961-11eb-9826-587be990916e.png)

I tried `npm i --save @unimodules/core` and then got these errors

![Screenshot 2021-05-20 at 11 32 01](https://user-images.githubusercontent.com/40716695/118966716-c7cd0300-b961-11eb-8fd5-f01dd93645ef.png)

![Screenshot 2021-05-20 at 11 33 34](https://user-images.githubusercontent.com/40716695/118966736-c996c680-b961-11eb-95e4-3cf95c91bb43.png)

It feels like Expo is destructively creeping into my project, and I would rather understand these issues rather than patch the packages in the errors until it works. 

```
"react-native-web": "0.16.0",
 "react-native-web-jsonschema-form": "3.1.5",
 "react-native-web-ui-components": "6.0.1",
```

Please let me know if this is irrelevant to this repo!

Thanks again for the the project.

Alfie

**Comment by runticle** [comment]
Don't worry, just compatibility issues with the web-ui-components library. Will stumble through it.

**Comment by CareLuLu-Gabriel** [comment]
@runticle sorry to hear it's not working. Just to understand, are you using Expo or not using Expo?

**Comment by runticle** [comment]
Sorry, we are _not_ using Expo. We have managed to fix by patching quite a lot of the of the web-ui-components package that we didn't need, which reduced the bundle size anyway. Win win for us in the end. Thanks for the response, I imagine this was one on us.

**Comment by CareLuLu-Gabriel** [comment]
@runticle that's great!

I do want to decouple the library from Expo. I think there are not that many changes in the library to make it work. Would you be interested in contributing?

**Comment by sckumar** [comment]
@runticle I also wanted to integrate this into the non Expo apps. Could you please share any sample references or direct me on how to make this work in react-native apps?

**Comment by runticle** [comment]
Hi both, sorry for the long absence - been very busy of course! I will have a refreshing look this week as it's been a while. Will get back to you @sckumar
