### ISSUE TITLE
onChange event values object contains old data

### ISSUE THREAD

**Issue by trajano** [CareLuLu/react-native-web-jsonschema-form#254]
The form event when there's a change has a `values` element but it contains only the older values and not the updated one.

## Expected Behavior
```
{
  "name": "change",
  "params": Object {
    "metas": Object {
      "artifacts": Array [],
      "description": Object {
        "ui:disabled": false,
      },
      "id": Object {
        "ui:disabled": false,
      },
      "moment_title": Object {
        "ui:disabled": false,
      },
      "signature": Object {
        "ui:disabled": false,
      },
    },
    "name": "moment_title",
    "nextErrors": false,
    "nextMeta": false,
    "path": "moment_title",
    "silent": false,
    "update": Array [
      "moment_title",
    ],
    "value": "change the world",
    "values": Object {
      "artifacts": Array [],
      "description": "",
      "id": "1X6nf5ZeRcGFuVZ2EyjMWC",
      "moment_title": "change the world",
      "signature": "4OkP36aDYxiIxsLOien9",
    },
  },
  "prevented": false,
}
```

## Current Behavior

```json
{
  "name": "change",
  "params": Object {
    "metas": Object {
      "artifacts": Array [],
      "description": Object {
        "ui:disabled": false,
      },
      "id": Object {
        "ui:disabled": false,
      },
      "moment_title": Object {
        "ui:disabled": false,
      },
      "signature": Object {
        "ui:disabled": false,
      },
    },
    "name": "moment_title",
    "nextErrors": false,
    "nextMeta": false,
    "path": "moment_title",
    "silent": false,
    "update": Array [
      "moment_title",
    ],
    "value": "change the world",
    "values": Object {
      "artifacts": Array [],
      "description": "",
      "id": "1X6nf5ZeRcGFuVZ2EyjMWC",
      "moment_title": "testtestsetest",
      "signature": "4OkP36aDYxiIxsLOien9",
    },
  },
  "prevented": false,
}
```

## Steps to Reproduce (for bugs)

1. create a handler that just writes the event out and have it referenced in the form tag

```
  const handleSave = async (event) => {
    console.log(event)
  };

<Form
                formData={form.form_data}
                schema={form.json_schema}
                uiSchema={form.ui_schema}
                widgets={{
                  CheckboxesWidget,
                  MarkdownWidget,
                  RadioWidget,
                  RangeWidget,
                  HeadingWidget,
                  SelectWidget,
                  MediaWidget,
                }}
                onChange={handleSave}
              ...
              />
```

2.  Change a field 
2. Select another field
3.
4.

## Context

I want to save the data to the database when there's a change so there's no need for an explicit save button.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by carelulu-igor** [comment]
Hey @trajano, thank you for your comment. Let me try to help you on this issue.
I tested it myself and got the following response (I started with an empty form). So may I ask you to please post your complete form (with uiSchema and all)?

Here's the result I got:
1st change - change "name" field
```js
{
  params: {
    name: "name"
    update: ["name"]
    value: "test"
    values: {
      name: "test"
      visible: null
    }
}
```
2nd change - change "name" field again
```js
{
  params: {
    name: "name"
    update: ["name"]
    value: "test 123"
    values: {
      name: "test 123"
      visible: null
    }
}
```
3rd change - change "visible" field
```js
{
  params: {
    name: "visible"
    update: ["visible"]
    value: "false"
    values: {
      name: "test 123"
      visible: false
    }
}
```

**Comment by trajano** [comment]
Sure thing, this is legacy code I am working on last night, but it appears to be working on your side.  There's one possibilityI can think of on my end.

* we use `ThemeProvider` which provides custom controls which I am now suspecting.

I am going to see if I can create a MVCE that shows it works (or not)

**Comment by trajano** [comment]
Ok I got an MVCE that shows the error I am describing.  Going to push it up shortly.

**Comment by trajano** [comment]
Starting state.  (starting from finished building...) no output yet
![image](https://user-images.githubusercontent.com/110627/122445711-cd713500-cf6f-11eb-95cc-0478a6e8de9d.png)
Typed `test` in the first field, nothing appearing yet (as expected) since I haven't lost focus on the field
![image](https://user-images.githubusercontent.com/110627/122445793-e37ef580-cf6f-11eb-93f0-5d3108187b1a.png)
went to description, from the logs `values` do not contain `test` value
![image](https://user-images.githubusercontent.com/110627/122445820-eda0f400-cf6f-11eb-9da8-58dffe484514.png)
Filled in after change on the description field and switched to title field, the description text is not in values but the `test` title appears in the logs
![image](https://user-images.githubusercontent.com/110627/122445959-1aeda200-cf70-11eb-89a7-3e28df951e04.png)

**Comment by trajano** [comment]
OK I found the solution.  It was a bit tricky and a little more advanced Javascript object manipulation.  But basically I changed my code to use your sample for onChange.  It triggered a re-render so the focus gets lost when that occurs.  But I saw how you set the params value as such I changed my code to do

```
  const onChangeLogging = (event) => {
    console.log({
      ...event.params.values,
      [event.params.name]: event.params.value,
    });
  };
```

It seems that's how you expect people to apply the changes but it is not obvious on the README file.  Closing for now since I have a solution for this.  Feel free to re-open if you want to use this to track a documentation update.

**Comment by CareLuLu-Gabriel** [comment]
@trajano thank you for debugging the problem. 

> It seems that's how you expect people to apply the changes

I don't think you need to apply changes. The form is uncontrolled. 

Is that what you need?
```js
const handleSave = async (event) => {
  // call API to save changes...  or just log them...
};

return (
  <Form
    {/* not needed: formData={form.form_data} */}
    schema={form.json_schema}
    uiSchema={form.ui_schema}
    widgets={{
      CheckboxesWidget,
      MarkdownWidget,
      RadioWidget,
      RangeWidget,
      HeadingWidget,
      SelectWidget,
      MediaWidget,
    }}
    onChange={handleSave}
  />
);
```

Another way to use this is by giving a fixed reference:
```js
const [formData] = useState(initialFormData);

const handleSave = async (event) => {
  // call API to save changes...  or just log them...
};

return (
  <Form
    formData={formData}
    schema={form.json_schema}
    uiSchema={form.ui_schema}
    widgets={{
      CheckboxesWidget,
      MarkdownWidget,
      RadioWidget,
      RangeWidget,
      HeadingWidget,
      SelectWidget,
      MediaWidget,
    }}
    onChange={handleSave}
  />
);
```

**Comment by trajano** [comment]
@CareLuLu-Gabriel  actually my original problem is because the `values` data is the old one.  I have to apply the changes.  This is demonstrated in https://github.com/trajano/rnjf-mvce/tree/6a610c636261b0a7deedd610a7af8e9c5dfbd959

Also the `onChange` changing the state as your last comment had shown forces a rerender and we lose focus I did that in https://github.com/trajano/rnjf-mvce/commit/e9b0d68dbca8bf97940f53ac1716fa85012a0031

**Comment by CareLuLu-Gabriel** [comment]
@trajano got it! Yes, `onChangeSample` will cause the form to re-render (potentially losing focus). `onChangeLogging` will have the new value in `name` and `value`, and the current `formData` in `values`.

We had initially not added the new value to `values` because the event can be canceled/prevented but we may consider changing that in the future. Thank you for pointing that out.

**Comment by trajano** [comment]
um please don't :) instead use `updatedValues` so it won't break existing code.

**Comment by CareLuLu-Gabriel** [comment]
Great idea! Would you have time to send a PR @trajano?

**Comment by trajano** [comment]
It's probably best if you switch to TypeScript so it will be given for "free".

**Comment by CareLuLu-Gabriel** [comment]
Using TS is something we want to do but haven't had the time to convert the library. 

If you want to contribute, feel free to send a PR. It be a great help 🙂

**Comment by trajano** [comment]
I'll see what I can do. no promises though.

**Comment by trajano** [comment]
@CareLuLu-Gabriel  I just posted my initial cut with the components I am using and linked it to https://github.com/CareLuLu/react-native-web-jsonschema-form/issues/256
