### ISSUE TITLE
Provide typings

### ISSUE THREAD

**Issue by trajano** [CareLuLu/react-native-web-jsonschema-form#256]
Your issue may already be reported!
Please search on the [issue tracker](../../issues) before creating one.

## Expected Behavior

Typescript typings should be added so we can leverage autocomplete on IDEs.

## Current Behavior

There's no typings

## Possible Solution

* Convert to TypeScript (very complex)
* Provide a .d.ts file as a stop-gap. (easier and isolated)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by carelulu-igor** [comment]
This issue has been resolved on the merged PRs listed above.
